### ISSUE TITLE
using a component as title in a column definition can cause massive performance issues

### ISSUE THREAD

**Issue by paintier** [material-table-core/core#111]
Hi all,

the [ componentDidUpdate()](https://github.com/material-table-core/core/blob/bc64a602f7d3d571fb1d1689e4da1bb9113c8efb/src/material-table.js#L134) method in `material-table.js` calls `equal` to figure out if the columns definition has changed. 

This can lead a big performance issues if the `title` attribute is a component, e.g. 
```typescript
const columns = [
  {
    title: <FancyHeader />,
    field: 'some_field'
  }
...
]
```
see also [this bugreport](https://github.com/facebook/react/issues/15397) which describes why comparing two components using "equal" is a bad idea. 

In edge cases this can lead to "maximum stack size exceeded" error messages.

Unfortunately there seems to exist no easy way to figure out if two react-components are rendered identically, so IMHO it would be best to consider the column definitions to have changed if the title attribute is a component and skip the equals test.

**Comment by matthewoestreich** [comment]
I think I'm following what you're saying.. but aren't we comparing two JavaScript objects? Not two React components? 

Couldn't it cause issues elsewhere skipping the check (if the title is is an Element)? 

>So it is easy to cause "Maximum call stack exceeded" error when developer compares props.children in deep way

^^ quote from bug report

Lastly, as the bugreport states, you shouldn't compare `children`, as in `props.children`, using `equal`, which we are not. We are using `equal` to compare two JS objects..  eg. `{ foo: "bar" } === { foo: "baz" } ? true : false`

**Comment by paintier** [comment]
> .. but aren't we comparing two JavaScript objects? Not two React components?

If the "title" Attribute in the columns object is a React component, then it ends up comparing components (and their children). 

Please have a look at this [Codepen Example](https://codesandbox.io/s/material-table-starter-template-forked-s2b3v?file=/src/index.js). I added a console.log() statement to show the contents of the `columns` object. Please have a look a `components[0].title`, and try to follow the `_owner.alternate.alternate.alternate....` property. 

Two things can happen:

* The `_owner.alternate.` structure is recursive: maximum stack size exceeded error. 
* The `_owner.alternate.` structure is not recursive: equal(old, new) follows the _owner.alternate structure until it finds a difference

In the provided example it finds a difference after follwing `_owner.alternate` about 4 times, **but** this heavily depends on the component.

**Comment by Domino987** [comment]
@paintier I checked out your codepen and the default time of the equal check is around 0.02587890625ms. Are you sure that this causes the problems? Or can you create an example where the "maximum stack size exceeded" errors is thrown?

**Comment by paintier** [comment]
It actually happens in my production code which I cannot share here, maybe I'll find a way to extract the problematic part which causes the infinite recursion, but that might take a while

**Comment by thefat32** [comment]
fast-deep-equal has a custom implementation for react elements

> To use with React (avoiding the traversal of React elements' _owner property that contains circular references and is not needed when comparing the elements - borrowed from react-fast-compare):

```ts
var equal = require('fast-deep-equal/react');
var equal = require('fast-deep-equal/es6/react');
```
It could help in such case, you can also use memos for title objects till this is resolved

**Comment by matthewoestreich** [comment]
Should we use that in this library? @peacechen @Domino987

**Comment by peacechen** [comment]
That looks like a great solution 👍

FYI: This project is already using `fast-deep-equal`. 
https://github.com/material-table-core/core/blob/bc64a602f7d3d571fb1d1689e4da1bb9113c8efb/src/material-table.js#L12

Should be able to simply change that line to
```import equal from 'fast-deep-equal/react';```

**Comment by Domino987** [comment]
Yes this looks good. Can we create a PR?

**Comment by matthewoestreich** [comment]
I went ahead and made this change. If the following is correct, just let me know and I will publish a new version.

Thanks everyone!!

https://github.com/material-table-core/core/blob/e880710fc5468b02b399871573edb5883c24c2da/src/material-table.js#L12

**Comment by Domino987** [comment]
I will close this, since it should be fixed with the new equal. Thanks everybody.

**Comment by BrenoVelasco** [comment]
Hi everyone! Thank you so much for changing the `equal` method.

I'm still facing this issue but it seems to be also related with the `react-intl` library, specifically the `FormattedMessage` component (which returns a component).
I created a `t()` function that wraps this `FormattedMessage` component and, every time I use it as column title definition, it throws me a `Maximum call stack size exceeded at getAllKeys at baseClone [...]`.

This is the code that causes the issue mentioned above:
<img width="553" alt="Screen Shot 2021-10-08 at 18 24 41" src="https://user-images.githubusercontent.com/21113340/136626342-475e8034-ae8c-4b36-873c-fbe82562127f.png">

This is a code that fixes that issue - the `intl.formatMessage` is an imperative way of invoking translation and it returns a raw string (not a component as `FormattedMessage` does).
<img width="567" alt="Screen Shot 2021-10-08 at 18 25 05" src="https://user-images.githubusercontent.com/21113340/136626385-ac280165-8b0d-4159-811e-d9ebc986fa94.png">
>

Thanks!

**Comment by Domino987** [comment]
Hi that's interesting, could you create a sandbox?

**Comment by BrenoVelasco** [comment]
Sorry, I tried to replicate but I can't share my company code here - it has a wrapper component that basically creates the entire screen with a header, header actions, table etc, so maybe I need to enhance its performance.
I created a small project here that would, hopefully, trigger the issue but it didn't so I won't even share it in a sandbox.

Anyway, if anyone is facing the same issue, just change to the imperative way, for columns titles, and you're good to go ;)

**Comment by mateenkasim** [comment]
I'm still getting the  "Maximum call stack exceeded" message, and it is still due to `fast-deep-equal`, which fails when comparing cyclic objects (i.e. object A references object B which references object A). See [here](https://github.com/epoberezkin/fast-deep-equal/issues/8).  As noted in this issue, they have a special case specifically for the `_owner` property on React components, but nothing else. This is causing MaterialTable to crash for me, since I have non-React circular objects.

I have a couple suggestions. One would be to change to a different package to get an `equal` function, perhaps `deep-eql` or lodash's `_.isEqual`. The other is to go the route Victory used [here](https://github.com/FormidableLabs/victory/issues/964#issuecomment-380185060) and use some try/catch statements to manually handle it. They just issue a warning and return `false`, but I'd hope to actually handle it in this case.

EDIT: Typos
