### ISSUE TITLE
Warning: Invalid prop `bulkEditChangedRows` of type `object` supplied to `MTableBody`

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#142]
**Describe the bug**

After updating to 2.23.29, a console warning started appearing:

> Warning: Failed prop type: Invalid prop `bulkEditChangedRows` of type `object` supplied to `MTableBody`, expected `array`.
>     in MTableBody (created by Droppable)
>     in Droppable (created by ConnectFunction)
>     in ConnectFunction
>     in ConnectFunction (created by MaterialTable)
>     in div
>     in Unknown (created by WithStyles(Component))
>     in WithStyles(Component) (created by MaterialTable)
>     in div (created by ForwardRef(Paper))
>     in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
>     in WithStyles(ForwardRef(Paper)) (created by Container)
>     in Container (created by ForwardRef(ContainerRef))
>     in ForwardRef(ContainerRef) (created by MaterialTable)
>     in Provider (created by App)
>     in App (created by ErrorBoundary)
>     in ErrorBoundary (created by DragDropContext)
>     in DragDropContext (created by MaterialTable)
>     in MaterialTable
> 

**To Reproduce**

The code is passing in edit props:
```
editable={{ onBulkUpdate, onRowDelete }}
```

Those are each functions. No direct reference to `bulkEditChangedRows` in my code.

**Expected behavior**
No warning

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome
- Version 86 (shouldn't matter)

**Comment by peacechen** [comment]
So... `bulkEditChangedRows` is indeed an object
https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L24

but the prop type is incorrectly set to array
https://github.com/material-table-core/core/blob/master/src/components/m-table-body.js#L332

**Comment by Domino987** [comment]
Good catch, Can you create a PR to address this?

**Comment by peacechen** [comment]
@Domino987 Yes I'll make one. Would you mind merging the prior PR #141 ?

Edit: I went ahead and pushed the fix for this too.  That PR covers two issues.

**Comment by Domino987** [comment]
Is this fixed now?

**Comment by moranbw** [comment]
I don't think it's been integrated yet?  Latest version still seems to be 2.3.29.  I'm still seeing the issue there.

**Comment by peacechen** [comment]
PR #141 was merged but release hasn't been published.

There are additional PR's that would be valuable to include in the next release.

@moranbw
If you need the fix immediately, you can point directly to my fork in your package.json.
```
    "@material-table/core": "https://github.com/peacechen/material-table-core#build",
```

**Comment by matthewoestreich** [comment]
This should be fixed now, since we have published a new version (v2.3.31) - please reopen if it is not fixed, or ping me and I will reopen (I did not notice this error during some work I did today, so it should be fixed).

Thanks everyone!
