### ISSUE TITLE
React 17.0.1 peer dependency warning

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#148]
**Describe the bug**

React 17.0.1 is listed as a peer dependency and results in warnings during install:

> npm WARN @material-table/core@2.3.29 requires a peer of react@^17.0.1 but none is installed. You must install peer dependencies yourself.
> npm WARN @material-table/core@2.3.29 requires a peer of react-dom@^17.0.1 but none is installed. You must install peer dependencies yourself.

First, recommend specifying only the major version in the peer dependency to allow for different minor versions (e.g. 17.0.2, etc).
Second, is React 17 truly a requirement for this library? We're using it successfully with React 16.x.

**To Reproduce**

> npm i

**Expected behavior**

No warnings with React 16

**Comment by FedeBev** [comment]
In addition to what was said by @peacechen, if you update react to v17 you get a new warning:
```
warning "@material-table/core > react-beautiful-dnd > use-memo-one@1.1.1" has incorrect peer dependency "react@^16.8.0".
```

**Comment by matthewoestreich** [comment]
Like this

https://github.com/material-table-core/core/blob/07fb84a78347cc1e7d032da55e4239eddd8ffdf8/package.json#L87-L88

and this?

https://github.com/material-table-core/core/blob/07fb84a78347cc1e7d032da55e4239eddd8ffdf8/package.json#L115-L116

If so, just let me know and I will publish a new version.

**Comment by peacechen** [comment]
Hooks were introduced in React 16.8.0, so should use that as the minimum version.

https://reactjs.org/docs/hooks-overview.html

**Comment by matthewoestreich** [comment]
Excellent point! I think this one can wait til tomorrow lol I'm about to crash. 

Thanks for all of your help today.

**Comment by sinclas** [comment]
Just tried to install this AM:  

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from @material-table/core@2.3.31
npm ERR! node_modules/@material-table/core
npm ERR!   @material-table/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Maybe go back a version of core or just wait for the dependencies to be resolved.  I think you may only need 16.8+?

**Comment by matthewoestreich** [comment]
This should be fixed now.

**Comment by sinclas** [comment]
Fixed!  Thank You.   Also, have to uninstall non branched version of material-table or you'll get install errors with a date dependency.

**Comment by sjdemartini** [comment]
I'm still seeing the issue mentioned here https://github.com/material-table-core/core/issues/148#issuecomment-823909965 due to the `react-beautiful-dnd` peer dependency:

```
warning "@material-table/core > react-beautiful-dnd@13.0.0" has incorrect peer dependency "react@^16.8.5".
warning "@material-table/core > react-beautiful-dnd@13.0.0" has incorrect peer dependency "react-dom@^16.8.5".
```

For that lib, as of 13.1.0 https://github.com/atlassian/react-beautiful-dnd/releases/tag/v13.1.0, React 17 should be supported, so theoretically bumping that peer dep to allow 13.1.0 should do the trick.
