### ISSUE TITLE
Detail Panel getting remounted on parent state change

### ISSUE THREAD

**Issue by mvitkin** [material-table-core/core#334]
**Describe the bug**
I have a `MaterialTable` with a detail panel containing another `MaterialTable`. The child table has a `onSelectionChange` property that modifies some state of the parent component. When I attempt to select one of the checkboxes of the child table, the detail panel is remounted and the checked boxes are lost.

CodeSandbox:
[![Edit material-table-starter-template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-table-starter-template-forked-fu8f7?fontsize=14&hidenavigation=1&theme=dark)

**To Reproduce**

1. Expand first row
2. Observe console log "sub-table mounted" (as expected)
3. Click on detail panel's checkbox
4. Check box does not get checked
5. Observe console, where sub-table logs being unmounted and remounted.

**Expected behavior**
Detail panel does not get remounted and check box gets checked

**Comment by Domino987** [comment]
This is connected on how react tracks states of components.

Since you are creating new render functions, those are not tracked. You need to create a stable reference so react can keep track of it:
```

const detailPanelCallback = React.useCallback(({ rowData }) => (
    <SubTable rowData={rowData} setSelection={setSelection} />
  ), [])

  return (
    <MaterialTable
      data={data}
      columns={columns}
      title="Starter Template"
      icons={tableIcons}
      detailPanel={detailPanelCallback}
      options={{
        selection: true
      }}
    />
  );
```

**Comment by mvitkin** [comment]
Thanks for the help @Domino987. `useCallback` does seem to fix it. However, I'm still a bit confused as to why this is causing a full remount rather than just a render. Unless there is a unique `key` prop changing somewhere, I think React should be smart enough to recognize this is the same component and save resources by re-rendering. I feel like I've passed in components like this in other places and not had issues with remounting.

Using `useCallback` like this also introduces other problems. If I want to pass any props into `SubTable`, those have to get added to `useCallback`'s dependency array, which means I now need to worry about maintaining the reference for those props as well, at risk of accidentally causing a remount on the grid.

**Comment by matthewoestreich** [comment]
@mvitkin I agree - something feels off about having to use `useCallback`. I believe we just published a new version which resolved and issue with comparing objects. Would you mind trying the latest version? 

@Domino987 I believe these issues started around the time we added that `id` prop. I wonder if we should focus on removing it and sticking to the `uuid` prop?

**Comment by mvitkin** [comment]
I tried with both the most recent release version (4.3.1), as well as the 0.2.0 pre-release. Unfortunately the issue still seems to be present :(

I can dig into this more later, but I took a look inside [m-table-detailpanel](https://github.com/material-table-core/core/blob/master/src/components/m-table-detailpanel.js) and I see strange stuff going on with saving the detail panel function reference in a ref. There may be background that necessitates this that I'm not aware of, but at first glance this seems extraneous, and there could be something in there that is messing up React's ability to manage rendering correctly.

**Comment by bastienff** [comment]
I am having the same problem. When i try to dispatch and action inside detailPanel component it break everything. If i use an useCallback kinda fix it, but it broke the collapse function of the detailPanel.

**Comment by chris-jalon** [comment]
i'm experiencing the same issue. as in OPs example, we have a table within a detailpanel with state passed as props to checkboxes inside it. in the now unmaintained material-table, it would work with this hacky workaround: https://github.com/mbrn/material-table/issues/986#issuecomment-646628535

this along with everything suggested in this thread fails or rerenders with interruption and slowness in material-table-core.

this may be related to rowData not being an instance of the object from the original `data` array, losing reactivity.

**Comment by Domino987** [comment]
Can you guys check if the problem still persists.

**Comment by chris-jalon** [comment]
@Domino987 switching @mvitkin's example to 4.3.10 resolves the issue. i have a complex implementation with subtables in the detail panel that re-render the main row and it works reliably too.

as for detail panels, the warning you are aware of still remains: https://github.com/material-table-core/core/issues/381

so this seems resolved.

**Comment by Domino987** [comment]
Yes I will look into it probably next week. I will be closing this.
