### ISSUE TITLE
Large bundle size - mostly due to jspdf

### ISSUE THREAD

**Issue by masbaehr** [material-table-core/core#45]
Hi, in "memory" of this open issue of the original material-table;

https://github.com/mbrn/material-table/issues/2164

i think a solution of this should be found mid to long-term. The usage of jspdf is simply an overkill, it should be removed from the original project - and the export to PDF should be somehow externalized. 

So this would break 100% compatibility - but for this i'd simply make an exception as the bundle size is too big for a table component as it is now.

**Comment by matthewoestreich** [comment]
Hi! We recently changed the way this package is bundled. The [bundle size](https://www.npmjs.com/package/@material-table/core) is now 199kb (almost half of what it was). Would you say this is too big?

Furthermore, jspdf was never being bundled with this package (from what I could tell at least). Anywho, jspdf is now marked as an [external dependency](https://github.com/material-table-core/core/blob/master/esbuild.config.js#L45) and is for sure not being bundled now.

**Comment by masbaehr** [comment]
Hmm.. when i still used the latest mbrn version it was still bundled. Or somehow it triggered the bundling of jspdf erroneously. Anyways, i've now created a new source-map-explorer output of my bundle. jspdf is not used within the webapp in other places

It is seemingly still being included :/ Am i doing something wrong?

![image](https://user-images.githubusercontent.com/38694044/104154956-66f75200-53e6-11eb-8ba4-88669eca9701.png)

![image](https://user-images.githubusercontent.com/38694044/104154972-72e31400-53e6-11eb-86c4-e7d748473ff6.png)

**Comment by matthewoestreich** [comment]
Hey I noticed an issue with the new bundler and had to revert. I [published](https://www.npmjs.com/package/@material-table/core/v/2.2.8) a new package that is working correctly (so thanks for bringing this up lol).

It [does appear](https://bundlephobia.com/result?p=@material-table/core@2.2.8) `jspdf` consumes a large portion of the "bundle", although it isn't necessarily "bundled" with the package, it is required by our package (which I do not know, or understand, why it is included and will look more into that).

I created a new project and installed `@material-table/core` (`v2.2.8`) - this is a screenshot of what `node_modules/@material-table/core` looks like:

<img width="224" alt="Screen Shot 2021-01-11 at 2 08 21 AM" src="https://user-images.githubusercontent.com/21092343/104157962-ee769e00-53b1-11eb-9345-943b4d646f45.png">

**Comment by masbaehr** [comment]
![image](https://user-images.githubusercontent.com/38694044/104158671-17b51f80-53ee-11eb-880a-8af250397b2c.png)

This is the only file referencing the jspdf stuff (jspdf and jspdf-autotable)

**Comment by masbaehr** [comment]
Also react-beautiful-dnd in future could be replaced with something more leightweight. 
https://bundlephobia.com/result?p=sortablejs@1.13.0
Thanks for linking to bundlephobia, useful tool i did not know :D

**Comment by matthewoestreich** [comment]
I tried to implement [this](https://github.com/mbrn/material-table/issues/2164#issuecomment-658731507) idea, but it didn't work. I'm not sure if I just did it wrong or what... You can check out the [new version here](https://www.npmjs.com/package/@material-table/core/v/2.2.9)

Changes I made:

- https://github.com/material-table-core/core/blob/master/src/components/m-table-toolbar.js#L17 
- https://github.com/material-table-core/core/blob/master/src/components/m-table-toolbar.js#L87
- https://github.com/material-table-core/core/blob/master/src/utils/exportPdf.js

Would it be a bad idea to move those deps into `peerDependencies`?

**Comment by matthewoestreich** [comment]
@masbaehr 

>Also react-beautiful-dnd in future could be replaced with something more leightweight

Completely agree. There are a lot of changes that need to be made!

**Comment by masbaehr** [comment]
edit: removed as a better solution was found

**Comment by matthewoestreich** [comment]
It finally clicked what that other person meant. So I made these changes:

#### Got rid of the following `options`

   - `options.exportButton`
   - `options.exportCsv`
   - `options.exportPdf`
   - `options.exportFileName`
   -  `options.exportDelimiter`

#### Added the following option to `options`

  - [`options.exportMenu`](https://material-table-core.com/docs/api/props/mt_prop_options)

#### This is how you would use it

This way allows you to provide as many 'export menu items' as you wish, and you are not constrained by csv/pdf/hard coding.

```javascript
// ...
import { ExportCsv, ExportPdf } from '@material-table/core/exporters';
// ^^^ Now `jspdf` is only part of your bundle if you want it to be (only `ExportPdf` uses it).
// We had to change how exporting worked as well (eg. remove 
// default export handlers while provide the same functionality).

<MaterialTable 
  // ...
  options={{
    // ...
    exportMenu: [{
      label: 'Export PDF',
      exportFunc: (cols, datas) => ExportPdf(cols, datas, 'myPdfFileName')
    }, {
      label: 'Export CSV',
      exportFunc: (cols, datas) => ExportCsv(cols, datas, 'myCsvFileName')
    }, {
      label: 'Export MySpecialFileType',
      exportFunc: (cols, datas) => { /* whatever you wish */ }
    }]
  }}
/>
```

This also helps [with the bundle size](https://bundlephobia.com/result?p=@material-table/core@2.3.0) as `jspdf` is no longer included by default. Now just the others to figure out :)

A [new version](https://www.npmjs.com/package/@material-table/core/v/2.3.0) has been published with these changes.

#### This is what was changed, essentially..

https://github.com/material-table-core/core/blob/ac680b9ee3af0a1a1a701a57033e0513399fe5bc/src/components/m-table-toolbar.js#L204-L214

https://github.com/material-table-core/core/blob/ac680b9ee3af0a1a1a701a57033e0513399fe5bc/exporters/index.js#L1-L30

**Comment by masbaehr** [comment]
I can confirm jspdf is no longer included in the build when not using the export functionality 👍

**Comment by matthewoestreich** [comment]
Going to close this one out for now.

**Comment by harshmaur** [comment]
@oze4 Thanks for the release! This worked for us as well! However I found that there is another major cause for the increase in the bundle size. 

Our application already uses react-beautifil-dnd so that didnt contribute to the bundle size. From my observations, the major causes were
1. jspdf
2. material-ui 

It looks like the whole materail-ui is imported / or tree shaking isnt working properly with material-ui. Before adding material-table our material-ui dependency was 250KB after adding material-table material-ui dependency increased to 1.2 MB. 

I am happy to look at this over the weekend. In case you already know about this, let me know if there are quicker ways to solve this.

**Comment by matthewoestreich** [comment]
I was not aware the entire material UI library was being bundled. According to [bundlephobia](https://bundlephobia.com/result?p=@material-table/core@2.3.2) it's not being bundled. I'll take all the help I can get!

**Comment by harshmaur** [comment]
@oze4 the size of the material-ui/core isn't itself a problem, the problem is with the project's bundle, when it gets included, it seems the whole material ui is being imported. 

After installing material-table and removing material-ui's data-grid
![image](https://user-images.githubusercontent.com/12210058/104419454-7d480e00-559e-11eb-9da2-73588ef23f78.png)

Before installing material-table and keeping material-ui's data-grid
![image](https://user-images.githubusercontent.com/12210058/104419548-9ea8fa00-559e-11eb-89bf-78b06ee0bf94.png)

**Comment by matthewoestreich** [comment]
Right. I get that. 

This is something I'm going to have to look into (I can't reproduce it). Are you using `@material-table/core` or `mbrn/material-table`?

**Comment by harshmaur** [comment]
Okay @oze4, so I created a new project with just material-ui and @material-table/core. 

This is the size when I just added a material button to the project. 
![image](https://user-images.githubusercontent.com/12210058/104808168-63126800-580a-11eb-835c-39b9d824a70a.png)

As you can see, I only have Button.js imported from material-ui

This is when I add material-table from the getting started page https://material-table-core.com/docs/#installation

![image](https://user-images.githubusercontent.com/12210058/104808188-85a48100-580a-11eb-8d5f-6bf17eb4207f.png)

As you can see material-table now makes the whole material-ui load up.

**Comment by harshmaur** [comment]
@oze4 can you add a contributing guide?

**Comment by matthewoestreich** [comment]
@harshmaur

So after testing this, I would need to see how you are bundling your project in order to assist further. 

Here is what I did to test:

- Created a fresh create-react-app project, [and published it to GitHub](https://github.com/oze4/mtc-bundle-issues-poc)
- Installed `@material-ui/core`, `@material-ui/icons`, `@material-table/core`, `source-map-explorer`
- Built basic component after removing default files
- Created script, `yarn build:analyze` that builds, then analyzes the bundle

As you can see, I am not seeing the same results (my entire bundle is 884.06kb). Perhaps, you are not bundling your code with tree-shaking?  My POC shows that when bundled correctly, `@material-table/core` does not include all of `@material-ui` in it's bundle.

Maybe you can fork the repo above, and run `yarn install && yarn build:analyze` to see if you get similar results?

<img width="1678" alt="z" src="https://user-images.githubusercontent.com/21092343/104821688-36a71d80-5803-11eb-9aa4-a17eeb084bbd.png">

**Comment by matthewoestreich** [comment]
@harshmaur I'm going to close this out for now. Please feel free to open a new issue if you're still having problems.

**Comment by masbaehr** [comment]
@oze4 I don't get why things like SwipeableDrawer or Slider are bundled when not used in the application? Is this because somewhere inside material-table they are used?

**Comment by matthewoestreich** [comment]
That's a great question. I'm not the original author so I'd have to look into it. Somewhere down the line, some component is using it. Is it in our codebase, or does material-ui use it in a comment we are importing (this transitively importing it?).

**Comment by matthew-kusz** [comment]
@oze4 Is jspdf required to export to csv?

**Comment by matthewoestreich** [comment]
It is not (at least to my knowledge). Are you using exporters?

**Comment by matthew-kusz** [comment]
Yes, would I need to create my own to avoid jspdf? I'm assuming importing exporters is why it is needed.

**Comment by matthewoestreich** [comment]
I can clean up exporters tonight, so that when you use CSV you don't need jspdf.

Thanks for pointing this out! @matthew-kusz

**Comment by matthew-kusz** [comment]
Awesome, thanks for the quick response!

**Comment by matthewoestreich** [comment]
@matthew-kusz would you mind trying the newest release to see if it's still an issue?

**Comment by matthew-kusz** [comment]
Updated to version 2.3.18 and it looks like jspdf is still being included in the build despite only using `ExportCSV`.

**Comment by masbaehr** [comment]
And if you remove csv export ? also try deleting node_modules and lock file. I had some strange issues in the past which were solved by a proper new npm install

**Comment by matthew-kusz** [comment]
If I remove the csv export it works fine. Deleting node_modules and the lock file did not solve the problem.

**Comment by matthewoestreich** [comment]
@matthew-kusz I made some changes and published a new version (2.3.19).

Would you mind doing the following:

 - Update to latest version
 - Change import to: `import ExportCsv from '@material-table/core/exporters/csv';`

Please let me know if that solves this for you.

**Comment by matthew-kusz** [comment]
I no longer am having problems with jspdf it seems, but now I've been met with this:
```
Failed to minify the code from this file: 

 	./node_modules/@material-table/core/exporters/csv.js:4 

Read more here: http://bit.ly/2tRViJ9
```
The main reason I hoped to avoid jspdf was from it preventing us from creating a production build. But now it's csv.js that's causing it. I could not include exporting the data to a csv, or create my own way to do it, but the build-in functionality was exactly what I needed. I remember not having problems with exporting when I used material-table.

**Comment by matthewoestreich** [comment]
Let me make one more change. It's odd bc it's working on my end. We are in the midst of a refactor to functional components. You also had jspdf included in your bundle before, even if you weren't using the export feature whatsoever.

**Comment by matthewoestreich** [comment]
@matthew-kusz would you mind checking v2.3.20 please?

**Comment by matthewoestreich** [comment]
@matthew-kusz I tested this and everything worked as expected. JSPDF is not shown in my bundle now.

<img width="1675" alt="nojspdf" src="https://user-images.githubusercontent.com/21092343/105565354-f573a980-5ceb-11eb-91f2-188048e52e87.png">

**Comment by matthew-kusz** [comment]
I updated and I am still receiving the same error in the last comment I made.

**Comment by matthewoestreich** [comment]
@matthew-kusz I am not able to reproduce the issue you are having. How are you bundling your app? The issue appears to be related to your setup, no? 

Have you deleted `node_modules` and ran `npm install` again?

**Comment by matthewoestreich** [comment]
@matthew-kusz I made another change... would you mind testing v2.3.22?

**Comment by matthew-kusz** [comment]
Tested it on 2.3.22 and it works, thanks for your help!
