### ISSUE TITLE
Inline edit of rows uses callback in setState in functional component.

### ISSUE THREAD

**Issue by stefanvanderzanden** [material-table-core/core#64]
When editing a row, changing a cell causes an error to be logged to the console

```Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().```

Problem seems to be in `core/src/components/MTableEditRow/index.js`. Looks like callback in setState (L129 & L136) should be changed to a useEffect.

**Reproduce**
1. Create a table with one line of data and set the rows to be editble.
2. Edit the row (And when you type the error appears in your console)

**Comment by matthewoestreich** [comment]
What version are you on? @stefanvanderzanden 

Thanks for opening this!

**Comment by stefanvanderzanden** [comment]
Hi @oze4 I'm currently on 2.3.4

**Comment by matthewoestreich** [comment]
Ok cool. I just published v2.3.5 - mind testing it out? 

It *should* work, as I manually tested before publishing.

Thanks again @stefanvanderzanden !

**Comment by stefanvanderzanden** [comment]
Hi @oze4, 

It doesn't show the error in the console log. Thank you so much for the quick response. 

I did find one other thing, want me to create another ticket (looking into it now myself as well)

**Comment by oze4** [comment]
Please do :)  I am just digging into this codebase and it's been a tough read lol. 

I reverted back to all class based components but the issue persists. 

Still trying to find the source of the bug.

**Comment by matthewoestreich** [comment]
Sorry. Commented on the wrong issue. Yes, please create a separate issue :)
