### ISSUE TITLE
error when trying to group by column

### ISSUE THREAD

**Issue by andrei10k** [material-table-core/core#727]
hey

try to group by word column in the link below. you'll see this error: undefined is not an object (evaluating 'newGroup.grouping')

https://codesandbox.io/s/material-table-starter-template-forked-u58ig6?file=/src/index.js

Thanks

**Comment by arulprabhin** [comment]
![image](https://user-images.githubusercontent.com/93645929/214497298-7a057146-d84e-4ad4-a7cf-0f2b70c72681.png)
Same Here!
![image](https://user-images.githubusercontent.com/93645929/214497377-a20d80ad-fadb-4a20-a75e-895ea6b216df.png)

**Comment by Domino987** [comment]
Should be fixed with the next release

**Comment by andrei10k** [comment]
ty

**Comment by andrei10k** [comment]
@Domino987 this is still not fixed. not the grouping is not working atunci all. drag a column in the group by section and is not added

**Comment by Domino987** [comment]
Seems like draggable changed the id to force it to be a string. Will be fixed with the next release
