### ISSUE TITLE
Warning: `NaN` is an invalid value for the `marginLeft` css style property.

### ISSUE THREAD

**Issue by masbaehr** [material-table-core/core#75]
I think this had been posted in the mbrn project somewhere but maybe we can find the solution for it.

I'm not entirely sure yet when it happens. Just saw this in the console. Will try to isolate the issue and post more information

Stacktrace:

Warning: `NaN` is an invalid value for the `marginLeft` css style property.
    in span (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by ForwardRef(IconButton))
    in ForwardRef(IconButton) (created by WithStyles(ForwardRef(IconButton)))
    in WithStyles(ForwardRef(IconButton)) (created by ForwardRef(SwitchBase))
    in ForwardRef(SwitchBase) (created by WithStyles(ForwardRef(SwitchBase)))
    in WithStyles(ForwardRef(SwitchBase)) (created by ForwardRef(Checkbox))
    in ForwardRef(Checkbox) (created by WithStyles(ForwardRef(Checkbox)))
    in WithStyles(ForwardRef(Checkbox)) (created by MTableBodyRow)
    in td (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by MTableBodyRow)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by MTableBodyRow)
    in MTableBodyRow (created by MTableGroupRow)
    in MTableGroupRow (created by MTableBody)

**Comment by matthewoestreich** [comment]
Hey @masbaehr would you mind using the [starter template](https://stackblitz.com/edit/material-table-starter-template) to create a reproducible example?

**Comment by masbaehr** [comment]
Here is an example. Sorry for the delay, had to remove a lot of unneeded code ;)
Also i think i found out why it happens. It happens when defaultGroupOrder is used, and one of the data-sets does not have a value for the field in question. 

```javascript
import React, { useState, useEffect } from "react";
import MaterialTable from "@material-table/core";

function Debug(props) {

    
  const [data, setData] = useState([{
      id: "1", alpha: "alpha", beta: "beta", gamma: "gamma",
      id: "2", alpha: "alpha", beta: "beta"
  }]);
  const [columns, setColumns] = useState( [
    { title: 'ID', field: 'id', hidden: true },
    { title: 'Alpha', field: 'alpha' },
    { title: 'Beta', field: 'beta' },
    { title: 'Gamma', field: 'gamma' , defaultGroupOrder: 0 }
  ]);

    const [isloading, setisloading] = useState(false);


  return (
    <div>

            <MaterialTable 
            
            title={"TestTable"}
            columns={columns}
            data={data}
            isLoading={isloading}
            options={{
              selection: true,
              grouping: true,
              defaultExpanded: true,
            }}
            onSelectionChange={(rows) => {
               
            }}
            
          />
        
    </div>
  );
}

export default Debug;

```

**Comment by matthewoestreich** [comment]
No worries. Would you mind putting this in a Sandbox, per our guidelines?

**Comment by matthewoestreich** [comment]
Hello! If you are still experiencing this issue, please reopen. Otherwise, please provide the required Sandbox as it is just easier on everyone. 

I have not noticed this error, so it may be resolved.

**Comment by masbaehr** [comment]
Hi, I don't use material-table anymore , but here is the test copied & pasted into the starter template if someone wants to resolve the issue
https://stackblitz.com/edit/material-table-starter-template-zqbtun?file=index.js
Changed version to *.32 , still happens (See Console). I already explained above what triggers it.

BTW: the starter template makes it actually more time consuming, had to change the version, wait a shitload of time to verify ;) instead my code example can just be copied into the local editor to verify ;-)

**Comment by kylenguyen1014** [comment]
@oze4 
This issue was brought up in this [material-table issue #1707](https://github.com/mbrn/material-table/issues/1707), and there is a pull request [#2338](https://github.com/mbrn/material-table/pull/2338) which never got merged
@Domino987 also involved in this a little, then it just got all quiet

**Comment by matthewoestreich** [comment]
Neither @Domino987 or myself can merge code into mbrn/material-table. 

Do we know if this is still am issue with the latest version of this repo? v3.0.3 only asking because I think this may have been fixed. We have "ported" some PRs from mbrn/material-table as well, so I'm not sure if this was one of them.

**Comment by masbaehr** [comment]
Yes it still can happen with 3.0.3 

see: https://material-table-starter-template-v8xmvj.stackblitz.io
src: https://stackblitz.com/edit/material-table-starter-template-v8xmvj?file=package.json

**Comment by kylenguyen1014** [comment]
@oze4 I know you can't, that's why this repo exists 👍 .

And yes, I can confirm this problem still exists, I just tried to update from 2.0.12 (kinda fixed on this version) to 3.0.3 today and it appeared again

**Comment by matthewoestreich** [comment]
Thank you. @Domino987 is this something you're aware of or can I merge that PR from mbrn/material-table?

For some reason this issue sounds familiar (outside of this convo).

**Comment by Domino987** [comment]
I have not looked into this previously, but the change from the PR looks good, so yes. Let's merge it.

**Comment by matthewoestreich** [comment]
@masbaehr @kylenguyen1014 would you mind giving the latest version a try? v3.0.5 (I messed up 3.0.4)... 

Thanks for your patience, and I def apologize about that. One of the reasons we created this repo was to be able to keep it updated, etc.. so if you see any other PRs that could be merged please feel free to send one over or let us know!

**Comment by kylenguyen1014** [comment]
> Thank you. @Domino987 is this something you're aware of or can I merge that PR from mbrn/material-table?
> 
> For some reason this issue sounds familiar (outside of this convo).

@oze4 I bet it's familiar to you haha. If you look at the original issue in material-table [#1707](https://github.com/mbrn/material-table/issues/1707), you were the first one to submit a PR [(#1759)](https://github.com/mbrn/material-table/pull/1759), then it did not get merged because of another [commit ](https://github.com/mbrn/material-table/commit/0249979b6d912fa9d9f75a6a579cc3df66d6c5c5)(which you also submitted lol) override the previous .

Anyway, I can confirm that v3.0.5 fixed the bug.

**Comment by Domino987** [comment]
Perfect, i will close this since it works. Thanks everybody for getting this fixed.
